### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by sotha-sil**
First lab notebook ready for review @pratsingh

### CODE REVIEW

**Comment by pratsingh** [comment]
Good report, great description. Some changes: some minor spelling errors in the write-ups, also would recommend to use LateX in the write up (could make the integrals and formulas prettier.)
Code looks good, last part needs to be finished it looks like.

**Comment by pratsingh** [comment]
the Latex command is just dollar signs and then the latex commands in between

eg $\sigma$ = `$\sigma$`

**Comment by sotha-sil** [comment]
Lab1 is now complete on my end and ready to be graded @AlexSchuy

**Comment by AlexSchuy** [comment]
Hi,

Below, I've included my comments on your lab. I'll enter a grade on Canvas shortly. Also, in the future, **please note within your document which parts of your document pertain to which parts of the assignment**.

**Overall comments:**

Your detailed discussion and plotting is excellent, very good job on this lab. I do have one note on plotting; in some sections, there are too many plots. Specifically, consider plotting multiple distributions within a single plot where possible. If that won't be clean, you can plot related quantities next to each other using plt.subplot. Also, make sure to always have a title for each plot, and to include legends and text boxes where additional information would be useful. Plots are a key part of all scientific communication, and the more the reader can understand about a plot without relying on other information, the better.

One other minor point; although this class is not a software engineering class, if you are going to repeat essentially the same code block several times, consider factoring it into a function. That, along with the plotting changes, will really help to reduce the dead space in your document (and usually reduce the rate of errors).

**Part 1: Problem 1**

1.B) Good, but you should explicitly compare to the linked z-table, as requested, " [...] make sure you are getting values that match the z-table."

1.C) Good.

1.D) Good (note: as I mention above, the answers to individual questions should be separated and clearly identifiable within the document).

**Part 1: Problem 2**

2.B) Excellent. One minor note is that you could relate the `scale` parameter to the definition of the Rayleigh distribution. Specifically, for a Rayleigh distribution, the 'scale' is typically denoted by sigma, as the Rayleigh distribution is the square root of the sum of the squares of two independent random variables that follow a normal distribution which has a standard deviation equal to `scale`.

**Part 1: Problem 3**

3.B/C/D/E) Excellent. 

**Part 1: Problem 4**

Excellent.

**Part 2: Problem 1**

1.B/C) Good. As a parenthetical, the pmf of the Poisson distribution does not reduce to the delta function, as the pmf is discrete, not continuous (you could consider a pdf, in which case it would reduce to this). You could say that P(k) = delta_{0, k} (the Kronecker delta), however, it would be just as clear to say that P(k = 0) = 1; there is no reason to use more sophisticated mathematical machinery than is helpful.

1.D) Good. 

1.E) Excellent. The mathematical discussion is nice. As another parenthetical, it's nice to be careful in the broader mathematical context about relating discreteness and countability. You might be tempted to claim that you cannot map the integers to the real numbers, as the integers are a discrete set and the real numbers are uncountably infinite. However, saying that a set is 'discrete' implicitly relies on a topological space in which the discrete set is embedded, and in fact it is possible to have a sufficiently 'large' topology such that a subset of the space is uncountably infinite and discrete.

Good job!

**Pull request merged**
